---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: laptop
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - alebastr/sway-extras
        - erikreider/SwayNotificationCenter
        - tofik/nwg-shell
        - solopasha/hyprland
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      packages:
        # System Integration
        - gdm
        - hyprland
        - libnotify
        - qt5-qtwayland
        - qt6-qtwayland
        - python3-gobject
        - zsh

        # Desktop Applications
        - thunderbird
        - nautilus
        - evince
        - kitty
        - vim
        - gnome-system-monitor
        - keepassxc

        # Desktop Utilities
        - wlogout
        - rofi-wayland
        - SwayNotificationCenter
        - waybar
        - waypaper
        - hyprshot
        - wf-recorder
        - swappy
        - nwg-dock-hyprland
        - rofimoji

        # Networking
        - blueman
        - nm-connection-editor
        - network-manager-applet
        - NetworkManager-tui
        - tailscale

        # Containers & Build Tools
        - podman
        - podman-compose
        - make
        - clang

        # System Utilities
        - rsync
        - fuse
        - ImageMagick

        # Device Support
        - libmtp
        - gvfs-mtp

        # audio libs
        - pipewire-jack-audio-connection-kit-devel

        # image libs
        - pango
        - pango-devel

  - type: script
    snippets:
      - "curl -L https://github.com/ReimuNotMoe/ydotool/releases/download/v1.0.4/ydotoold-release-ubuntu-latest -o /usr/bin/yodotoold"
      - "chmod +x /usr/bin/yodotoold"
      - "chmod +x /usr/bin/grub2-mkconfig-patched"

    scripts:
      - install_appimagelauncher.sh

  - type: default-flatpaks
    configurations:
      - notify: true

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.gnome.Loupe
          - org.videolan.VLC
          - com.logseq.Logseq
          - org.gnome.baobab
          - com.github.tchx84.Flatseal
          - org.zotero.Zotero
          - org.gnome.Calendar

      - notify: true
        scope: user
        repo:
          url: https://mylinuxforwork.github.io/ml4w-flatpak-repo/ml4w-apps.flatpakrepo
          name: ml4w
          title: ML4W
        install:
          - com.ml4w.calendar

      - scope: user # Also add Flathub user repo, but no user packages

  - type: chezmoi
    repository: https://github.com/rambip/dotfiles

  - type: systemd
    user:
      enabled:
        - ssh-agent.service
    system:
      enabled:
        - chronyd.service
        - grub-setup.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
