---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: laptop
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - lihaohong/yazi
        # usefull ?
        - alebastr/sway-extras
        - erikreider/SwayNotificationCenter
        - tofik/nwg-shell
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      packages:
        # Term
        - starship
        - zsh
        - bat
        - yazi
        - toilet
        # DE
        - hyprland
        - libnotify
        - qt5-qtwayland
        - qt6-qtwayland
        - uwsm # remove ?
        - python3-gobject # remove ?
        - rofi-wayland
        - SwayNotificationCenter
        - kitty
        - vim
        - nm-connection-editor
        - network-manager-applet
        - NetworkManager-tui
        - waypaper
        - https://github.com/charmbracelet/gum/releases/download/v0.17.0/gum-0.17.0-1.x86_64.rpm
        # Utils
        - tailscale
        - rsync
        - fuse
        - ImageMagick
        - jq
        #- cliphist

      #exclude:
      #  - alacritty
      #  - waybar
      #  - waybar-git
      #  - fuzzel
      #  - mako
      #  - swaybg
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - htop

  - type: script
    snippets:
      - "curl https://github.com/sentriz/cliphist/releases/download/v0.7.0/v0.7.0-linux-amd64 -o /usr/bin/cliphist"
      - "curl https://github.com/jacobdeichert/mask/releases/download/mask%2F0.11.6/mask-0.11.6-x86_64-unknown-linux-gnu.zip -o /usr/bin/mask"
      - "curl https://github.com/InioX/matugen/releases/download/v3.0.0/matugen-3.0.0-x86_64.tar.gz -o /usr/bin/matugen"

  - type: fonts
    fonts:
      nerd-fonts:
        - IBMPlexMono
        - FiraCode
      google-fonts:
        - Dancing Script
        - Pacifico
        - Lobster
        - Caveat
        - Twinkle Star

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
          - org.mozilla.thunderbird
          - org.videolan.VLC
          - com.logseq.Logseq
          - org.gnome.baobab
          - com.github.tchx84.Flatseal
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
